version: "3"
services:
  db_postgres:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    restart: unless-stopped

  # APP*****************************************
  api_proposta:
    build: ./proposta
    expose:
      - 8300
    ports:
      - 8300:8300
    depends_on:
      - db_postgres
    links:
      - db_postgres

  api_credito:
    build: ./credito
    expose:
      - 8400
    ports:
      - 8400:8400
    restart: unless-stopped
    depends_on:
      - db_postgres
      - api_proposta
    links:
      - db_postgres
  front:
    build: ./front
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - db_postgres
      - api_proposta
      - api_credito
    links:
      - api_proposta
      - api_credito
volumes:
  postgres-data:
